apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-cert-manager-sa-tokenrequest
  namespace: prometheus-graphana
subjects:
  - kind: ServiceAccount
    name: cert-manager-sa
    namespace: prometheus-graphana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-sa-tokenrequest
