apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-sa-tokenrequest
  namespace: istio-system
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    resourceNames: ["cert-manager-sa"]
    verbs: ["create"]
