apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  # namespace: prometheus-grafana
  namespace: istio-system
spec:
  secretName: grafana-cert-tls
  dnsNames:
    - grafanav1.shyammylai.me
  issuerRef:
    name: grafana-letsencrypt-prod
    kind: Issuer
