apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana-gateway
  # namespace: istio-system
  namespace: prometheus-graphana
spec:
  selector:
    istio: gateway 
    # app: app=istio-gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port: 
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - grafana.shyammylai.me
    tls:
      # httpsRedirect: true
      mode: SIMPLE
      credentialName: grafana-cert-tls
      # credentialName: cert-manager-webhook-ca
