apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: llm-letsencrypt-prod
  # namespace: prometheus-grafana
  namespace: istio-system
spec:
  acme:
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ubalasubramanian03@gmail.com
    privateKeySecretRef:
      name: llm-letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
            - "llm.shyammylai.me"
        dns01:
          route53:
            region: us-east-1
            role: arn:aws:iam::851725214337:role/eks_route53_role
            auth:
              kubernetes:
                serviceAccountRef:
                  name: cert-manager-sa
