apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: llm-cert
  # namespace: prometheus-grafana
  namespace: istio-system
spec:
  secretName: llm-cert-tls
  dnsNames:
    - llm.shyammylai.me
  issuerRef:
    name: llm-letsencrypt-prod
    kind: Issuer
