fullnameOverride: "cve-webapp-db"
service:
  type: "LoadBalancer"

persistance:
  storageClass: "ebc-sc"
  size: "4Gi"

postgresql:
  username: "cve_user"
  password: "cve123"
  database: "cve"
  repmgrUsername: "repmgr"
  repmgrPassword: "repmgr123"

  podLabels:
    networkLabel: "db"
    sidecar.istio.io/inject: "false"
  networkPolicy:
    enabled: true
    allowExternal: false
    extraIngress:
      - from:
          - podSelector:
              matchLabels:
                app: deployment-consumer # label for kafka-consumer pod
          - namespaceSelector:
              matchLabels:
                namespace: namespace3
      - from:
          - podSelector:
              matchLabels:
                pg-network-policy: "true"
          - namespaceSelector: {}
  resources:
    requests:
      cpu: "300m"
      memory: "512Mi"
      ephemeral-storage: "50Mi"
    limits:
      cpu: "500m"
      memory: "1024Mi"
      ephemeral-storage: "2Gi"

pgpool:
  adminUsername: "pgpool"
  adminPassword: "admin123"
  podLabels:
    networkLabel: "db"
    sidecar.istio.io/inject: "false"
  networkPolicy:
    enabled: true
    allowExternal: false
    extraIngress:
      - from:
          - podSelector:
              matchLabels:
                app: deployment-consumer # label for kafka-consumer pod
          - namespaceSelector:
              matchLabels:
                namespace: namespace3
      - from:
          - podSelector:
              matchLabels:
                pg-network-policy: "true"
          - namespaceSelector: {}
  resources:
    requests:
      cpu: "300m"
      memory: "512Mi"
      ephemeral-storage: "50Mi"
    limits:
      cpu: "500m"
      memory: "1024Mi"
      ephemeral-storage: "2Gi"

metrics: 
  enabled: true
  image:
    repository: prometheuscommunity/postgres-exporter
    tag: "master"
    pullPolicy: IfNotPresent
