fullnameOverride: "cve-webapp-db"
service: 
  type: "LoadBalancer"

persistance:
  storageClass: "ebc-sc"
  size: "4Gi"

postgresql:
  username: "cve_user"
  password: "cve123"
  database: "cve"
  repmgrUsername: "repmgr"
  repmgrPassword: "repmgr123"
  podLabels: 
    networkLabel: "db"
  networkPolicy: 
    enabled: true
    allowExternal: false
    extraIngress: 
      - from:
          - podSelector:
              matchLabels:
                app: deployment-consumer # label for kafka-consumer pod
          - namespaceSelector:
              matchLabels:
                namespace: namespace3
      

pgpool:
  adminUsername: "pgpool"
  adminPassword: "admin123"
  podLabels: 
    networkLabel: "db"
  networkPolicy: 
    enabled: true
    allowExternal: false
    extraIngress: 
      - from:
          - podSelector:
              matchLabels:
                app: deployment-consumer # label for kafka-consumer pod
          - namespaceSelector:
              matchLabels:
                namespace: namespace3
