apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-virtual-service
  namespace: prometheus-graphana
spec:
  hosts:
  - grafana.shyammylai.me  # Or your specific domain
  gateways:
  # - istio-system/grafana-gateway
  - prometheus-graphana/grafana-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: graphana-prometheus-grafana.prometheus-graphana.svc.cluster.local
        port:
          number: 80


